on:
  pull_request:
  merge_group:

jobs:
  fail-on-small-minutes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          minutes="$(date +%M)"
          last_digit="${minutes: -1}"
          test $last_digit -lt 6
          exit $?
  always_passing_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "evergreen"
