on:
  pull_request:
  merge_group:

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -x
          COMMIT_MESSAGE=$(git log --format=%B -n 1 $GITHUB_SHA)
          if [[ $COMMIT_MESSAGE =~ fail ]]; then
            echo failing as required
            exit 1
          fi
  always_passing_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "evergreen"          
